lotto/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'help' => 'lotto_pages#help'
  get 'about' => 'lotto_pages#about'
  get 'contact' => 'lotto_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :favorite_numbers
  resources :users

    root 'lotto_pages#home'

end

lotto/app/models/favorite_number.rb
class FavoriteNumber < ActiveRecord::Base
    belongs_to :user
    
end

lotto/app/models/user.rb
class User < ActiveRecord::Base
    has_many :favorite_numbers
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: true, length: { in: 4..20 }
    has_secure_password
    validates :password, presence: true, length: { in: 4..20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
    
  #return the hash digest of the given string
  def User.digest(str)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::ENGINE.cost
    BCrypt::Password.create(str, cost: cost)
  end
  
  #Returns random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  #Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  #Returns true if the given token matched the digest
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

lotto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  include SessionsHelper
  
  def index
  end
      
end

lotto/app/controllers/favorite_numbers_controller.rb
class FavoriteNumbersController < ApplicationController
  before_action :set_favorite_number, only: [:show, :edit, :update, :destroy]

  # GET /favorite_numbers
  # GET /favorite_numbers.json
  def index
    @favorite_numbers = FavoriteNumber.all
  end

  # GET /favorite_numbers/1
  # GET /favorite_numbers/1.json
  def show
  end

  # GET /favorite_numbers/new
  def new
    @favorite_number = FavoriteNumber.new
  end

  # GET /favorite_numbers/1/edit
  def edit
  end

  # POST /favorite_numbers
  # POST /favorite_numbers.json
  def create
    @favorite_number = FavoriteNumber.new(favorite_number_params)

    respond_to do |format|
      if @favorite_number.save
        format.html { redirect_to @favorite_number, notice: 'Favorite number was successfully created.' }
        format.json { render :show, status: :created, location: @favorite_number }
      else
        format.html { render :new }
        format.json { render json: @favorite_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_numbers/1
  # PATCH/PUT /favorite_numbers/1.json
  def update
    respond_to do |format|
      if @favorite_number.update(favorite_number_params)
        format.html { redirect_to @favorite_number, notice: 'Favorite number was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_number }
      else
        format.html { render :edit }
        format.json { render json: @favorite_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_numbers/1
  # DELETE /favorite_numbers/1.json
  def destroy
    @favorite_number.destroy
    respond_to do |format|
      format.html { redirect_to favorite_numbers_url, notice: 'Favorite number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_number
      @favorite_number = FavoriteNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_number_params
      params.require(:favorite_number).permit(:user_id, :num1, :num2, :num3, :num4, :num5, :num6, :num7)
    end
end

lotto/app/controllers/lotto_pages_controller.rb
class LottoPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
end

lotto/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #Log the user in and redirect to the user show page.
      log_in user
      remember token
      redirect_to user
    else
      flash.now[:danger] = 'sähköposti tai salasana väärin'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

lotto/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "Tervetuloa #{@user.username}"
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

lotto/app/helpers/application_helper.rb
module ApplicationHelper

#Return the full title on a per-page basis

  def full_title(page_title = '')
    base_title = "Lottosivut"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"    
    end
  end
end

lotto/app/helpers/favorite_numbers_helper.rb
module FavoriteNumbersHelper
end

lotto/app/helpers/lotto_pages_helper.rb
module LottoPagesHelper
end

lotto/app/helpers/sessions_helper.rb
module SessionsHelper
  #logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  #Return the current logged in user (if nay)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  #Returns true if user is logged in, false otherwise
  def loggeg_in?
    !current_user.nil?
  end
  
  #logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  #Remembers user in a persisten session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user_id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

lotto/app/helpers/users_helper.rb
module UsersHelper
  
  #returns gravatar for given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

lotto/app/views/favorite_numbers/_form.html.erb
<%= form_for(@favorite_number) do |f| %>
  <% if @favorite_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_number.errors.count, "error") %> prohibited this favorite_number from being saved:</h2>

      <ul>
      <% @favorite_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :num1 %><br>
    <%= f.number_field :num1 %>
  </div>
  <div class="field">
    <%= f.label :num2 %><br>
    <%= f.number_field :num2 %>
  </div>
  <div class="field">
    <%= f.label :num3 %><br>
    <%= f.number_field :num3 %>
  </div>
  <div class="field">
    <%= f.label :num4 %><br>
    <%= f.number_field :num4 %>
  </div>
  <div class="field">
    <%= f.label :num5 %><br>
    <%= f.number_field :num5 %>
  </div>
  <div class="field">
    <%= f.label :num6 %><br>
    <%= f.number_field :num6 %>
  </div>
  <div class="field">
    <%= f.label :num7 %><br>
    <%= f.number_field :num7 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lotto/app/views/favorite_numbers/edit.html.erb
<h1>Editing Favorite Number</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite_number %> |
<%= link_to 'Back', favorite_numbers_path %>

lotto/app/views/favorite_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favorite Numbers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Num1</th>
      <th>Num2</th>
      <th>Num3</th>
      <th>Num4</th>
      <th>Num5</th>
      <th>Num6</th>
      <th>Num7</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_numbers.each do |favorite_number| %>
      <tr>
        <td><%= favorite_number.user_id %></td>
        <td><%= favorite_number.num1 %></td>
        <td><%= favorite_number.num2 %></td>
        <td><%= favorite_number.num3 %></td>
        <td><%= favorite_number.num4 %></td>
        <td><%= favorite_number.num5 %></td>
        <td><%= favorite_number.num6 %></td>
        <td><%= favorite_number.num7 %></td>
        <td><%= link_to 'Show', favorite_number %></td>
        <td><%= link_to 'Edit', edit_favorite_number_path(favorite_number) %></td>
        <td><%= link_to 'Destroy', favorite_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite number', new_favorite_number_path %>

lotto/app/views/favorite_numbers/new.html.erb
<h1>New Favorite Number</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_numbers_path %>

lotto/app/views/favorite_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite_number.user_id %>
</p>

<p>
  <strong>Num1:</strong>
  <%= @favorite_number.num1 %>
</p>

<p>
  <strong>Num2:</strong>
  <%= @favorite_number.num2 %>
</p>

<p>
  <strong>Num3:</strong>
  <%= @favorite_number.num3 %>
</p>

<p>
  <strong>Num4:</strong>
  <%= @favorite_number.num4 %>
</p>

<p>
  <strong>Num5:</strong>
  <%= @favorite_number.num5 %>
</p>

<p>
  <strong>Num6:</strong>
  <%= @favorite_number.num6 %>
</p>

<p>
  <strong>Num7:</strong>
  <%= @favorite_number.num7 %>
</p>

<%= link_to 'Edit', edit_favorite_number_path(@favorite_number) %> |
<%= link_to 'Back', favorite_numbers_path %>

lotto/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Joku linkki <a href="#">linkki.fi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Tietoa", about_path %></li>
      <li><%= link_to "Yhteystiedot", contact_path %></li>
    </ul>
  </nav>
</footer>

lotto/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Lottosivuille", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Etusivu", root_path %></li>
       <li><%= link_to "Apua", help_path %></li>
       <% if loggeg_in? %>
       <li><%= link_to "Käyttäjät", "#" %> </li>
       <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Tili <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "Profiili", current_user %></li>
             <li><%= link_to "Asetukset", "#" %></li>
             <li class="divider"></li>
             <li>
               <li><%= link_to "Kirjaudu ulos", logout_path, method: "delete" %></li>
             </li>
           </ul>
       </li>
       <% else %>
        <li><%= link_to "Kirjaudu", login_path %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

lotto/app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

lotto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

lotto/app/views/lotto_pages/about.html.erb
<% provide(:title, "Tietoa") %>

    <h1>About lottosivut</h1>
    <p>Tänne about tieto sivustosta</p>

lotto/app/views/lotto_pages/contact.html.erb
<% provide(:title, 'Yhteystiedot') %>
<h1>Yhteystiedot</h1>
<p>
Tähän tulee yhteystiedot
</p>

lotto/app/views/lotto_pages/help.html.erb
<% provide(:title, "Apua") %>

    <h1>Lotto apua sivut</h1>
    <p>Tähän tulee lotto sivuille ohjeet</p>

lotto/app/views/lotto_pages/home.html.erb
<% provide(:title, "Etusivu") %>
<div class="center jumbotron">
  <h1>Lottosivu</h1>
  <h2>Tähän tulee perusinfo sivusta</h2>
  
  <%= link_to "Uusi käyttäjä", signup_path, class: "btn btn-lg btn-primary" %>
</div>

lotto/app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label 'Käyttäjätunnus' %><br>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label 'Salasana' %><br>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label 'Sähköposti' %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit 'Luo', class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>  
  </div>
</div>

lotto/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

lotto/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Käyttäjät</h1>

<table>
  <thead>
    <tr>
      <th>Käyttäjätunnus</th>
      <th>Salasana</th>
      <th>Sähköposti</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Näytä', user %></td>
        <td><%= link_to 'Muokkaa', edit_user_path(user) %></td>
        <td><%= link_to 'Poista', user, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Uusi käyttäjä', new_user_path %>

lotto/app/views/users/new.html.erb
<%= provide(:title, 'Uusi käyttäjä') %>

<h1>Uusi käyttäjä</h1>

<%= render 'form' %>

<%= link_to 'Takaisin', root_path %>

lotto/app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md4-4">
    <section class="user_info">
    <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>


<%= link_to 'Muokkaa', edit_user_path(@user) %> |
<%= link_to 'Takaisin', users_path %>